// <auto-generated />
using System;
using DigitalSolutionsStudio.Api.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalSolutionsStudio.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240903183652_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DigitalSolutionsStudio.Api.Db.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 9, 3, 21, 36, 52, 433, DateTimeKind.Local).AddTicks(2470),
                            Description = "First task",
                            LastModifiedDate = new DateTime(2024, 9, 3, 21, 36, 52, 433, DateTimeKind.Local).AddTicks(2488),
                            Name = "First task",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 9, 3, 21, 36, 52, 433, DateTimeKind.Local).AddTicks(2490),
                            Description = "Second task",
                            LastModifiedDate = new DateTime(2024, 9, 3, 21, 36, 52, 433, DateTimeKind.Local).AddTicks(2490),
                            Name = "First task",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 9, 3, 21, 36, 52, 433, DateTimeKind.Local).AddTicks(2491),
                            Description = "Third task",
                            LastModifiedDate = new DateTime(2024, 9, 3, 21, 36, 52, 433, DateTimeKind.Local).AddTicks(2492),
                            Name = "First task",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
